changeLogFile: changelog/db.changelog-master.sql
url: jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
username: postgres.wqdvgfhhjjeuspwdqndz
password: 181006Practicas
driver: org.postgresql.Driver
classpath: lib/postgresql-42.7.10.jar